---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  interval: 1h
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent-libtorrentv1
              tag: 5.2.0@sha256:84df7567235402431925d5d6ca763b744f612a3e02bfbe71cf64831bb59a08d3
            env:
              TZ: Europe/Zurich
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 31288
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 16Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.121.0@sha256:ea5f42d99998e2ba44297eca9b8a38a101e718ef54caaa41d649f6c6f1c8c71e
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
          http-code:
            port: 12321
            protocol: TCP
      bittorrent:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.69.123
        externalTrafficPolicy: Local
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.devtom.ch"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      code-server:
        hostnames:
          - "{{ .Release.Name }}-code.devtom.ch"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 12321
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: 192.168.4.69
        path: /storage/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
