apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ej7+SBRG0LrO5AQ818Z4vf/1zYmWnziaZngo1inkwEyTF7H3uYCQGQ==,iv:kVfWwd4d8Km5rwCJ3LTgsb/y+kdCvmKucr1tjWzBCTg=,tag:Zcj3BrmFBeFPJdsV+llg0w==,type:str]
sops:
  age:
    - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOEw5QmtFcE1nbUJKSTEw
        cGZEak02UVhpbUl0UHovazA4TEhBM0hNN0ZjCnFVaWdCOFNkY0krM2F1Y1hDRXI4
        aENvK1dZdnNEdEthbmljeEhPWlJQTW8KLS0tIFVYYnJyckM0d1IxUEloaTZGWis0
        Z0pSSTNJcVRYN2JRK1Q2ZE9lS0dLdjQKwmDaPbRC6AmhAz/3k5RHDREgJj/dx+IB
        boGWfqjFamTtUIZMQrAMzH0D3OCD/EDcHUZh/tGcn7cbYdOmsdJmuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T08:35:28Z"
  mac: ENC[AES256_GCM,data:/kUHPJoGWm3YPichnrbKARTCRrhdM55IOj7if6UqsNZHENSwTm0k0BvNeZ97z3ufoJ41DDVx/L+CIbW8eG+SpxS4DXTglIz9j265wc28nfcbjJvPgwb0sDQzqjaoVIx4pSVH3yuzVX7vV9UjhUzyG9l6gANLZPJa32Rl83Q8thg=,iv:UkWD342sg+vjAegDifia1Hs9UoKrTItvXkPl0Npumfw=,tag:i+jxlk6bSF1xfHfM0JksIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
