apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ej7+SBRG0LrO5AQ818Z4vf/1zYmWnziaZngo1inkwEyTF7H3uYCQGQ==,iv:kVfWwd4d8Km5rwCJ3LTgsb/y+kdCvmKucr1tjWzBCTg=,tag:Zcj3BrmFBeFPJdsV+llg0w==,type:str]
    zone-id: ENC[AES256_GCM,data:mU3o/iVqExdWQa95AXJMw4kHY2wA1J2hzA+/41caOXo=,iv:fCJeeM0nXxapTkpYJXaa8XcbLcR2kfUhQeWTCYHLmNI=,tag:D4g07CMhYEQ4bvR2iap3gQ==,type:str]
sops:
    age:
        - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOEw5QmtFcE1nbUJKSTEw
            cGZEak02UVhpbUl0UHovazA4TEhBM0hNN0ZjCnFVaWdCOFNkY0krM2F1Y1hDRXI4
            aENvK1dZdnNEdEthbmljeEhPWlJQTW8KLS0tIFVYYnJyckM0d1IxUEloaTZGWis0
            Z0pSSTNJcVRYN2JRK1Q2ZE9lS0dLdjQKwmDaPbRC6AmhAz/3k5RHDREgJj/dx+IB
            boGWfqjFamTtUIZMQrAMzH0D3OCD/EDcHUZh/tGcn7cbYdOmsdJmuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T14:42:45Z"
    mac: ENC[AES256_GCM,data:Zd4m/iFuqk/4V5dyAPYsXNQ5DeXFOat9zKpm4pu/qptcs8ziFw3wOzZjDutIvph2O3EUy3B7nrjnzhrsFTKR3dYhfW8m5MhovG9A2oXicLu4qLQpYnOSAgOzUyKa4EQ9m/d48oiHYgjFZpYbb7vMacE04foYQJ+Ig6+KQNZzei0=,iv:zL3xCpIdIb9D6AtUX94mwHFBFOJLiiXPcIqVWBNjvE8=,tag:EMmJIpoCXPmiU2hLMrDwbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
