apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VUsyE4c09rTb,iv:/d9/LcnAFo42bgkYxl18/KcQ+5iVMH+ivaiGjz7lY4Q=,tag:PKMJWquLZXBK/WtI5Nq7LA==,type:str]
sops:
  age:
    - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VTZmWkVaUDBFMkd5TDlE
        MDN0NGJEM2liRGxaaXlvdnRpZHFOK2RObWxvClhza2lEVlpRQmszek9ZTFQvbk95
        NzZlSFlHLzBBVTRFb25SejJmM1FORDgKLS0tIEJSY293a0tSYjJ3ZjBPS21ZSlVH
        MU1JUmRqcysyV3MrZ2FqbTVOZ3hzbTAKZceA+/tgjHt7R3d4cf4GgMnpDwLBqlgL
        NDeiwZYtHufNrEpwi7VI1eByUT7ghv1G7Q5O7OPUPW2OlQbUAmbYvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T08:35:28Z"
  mac: ENC[AES256_GCM,data:gfL29na56QBshX3VvpsH6W54wfpWGVRqr6tBgA8nG2yKO7q3xhOY3cchqPBW1NVwUcVX6ezuvLg79MIiB5+uqpLYlHYLr2h4Vq49iRmdaHhqmOcpg0urEkFasLZzYjbCiJ1G+UF82lvsv/ITSZ2+uVShMTxuWOkyiithxcfrAGg=,iv:l/MUUYh4Q1++aXyXBuZrftE3j2YVBC8wpWcT++O9ngE=,tag:zrfluQUkcKestT7/dfZJPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
