apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:cyKKQT4qxoYXCMjif/pKfyWq62bttUCQysiUag316NREQI5EyCBxCQ==,iv:5ZEJpTXptsbuuNtqSF7bd7+4FlF9Oei5eqw/T2ZyyEw=,tag:c82P9luWClqU8joxo7U4Bg==,type:str]
sops:
    age:
        - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOENXTnFoaW5kOFZPdytm
            bVgzd0NrdU1rZW5xM3ZFSHo3U01KNWRFd1J3CjB6ZlhBRExuaUU0QjE2NWdOTGVn
            T1RVME9SMlZpSS9vVTE0RkdNdmVMYVUKLS0tIDJObGwzTGpMME9YVzgzVldIVm4x
            Uy9YS1k0NDJYNUhBa0c3Y2xDNTZqbzQKxGbIGy1ny+Fngz/m6PD0zQaw/iFrhYkl
            TiyGzvsfMvSxifhlCxqR1rY/VaDLEZNwVwbL0a1F5QeYulrT+5B+2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T06:24:49Z"
    mac: ENC[AES256_GCM,data:YzanbFP35Ufskj2yf7wf+R0CamvPTm5OdrVRw4DGLmFWVTlj0b6oROXZm/ioTNYtGDRKQ22r9VKmxSXs0dWtVeKOCX2Iv+UXHERPPq1w3mvNXEQqEPDcmX54I0JBUZ1H0KpiE3A/GUbQat0fRtkari/4kYdSjkFtLO3vw9p1zWs=,iv:9NEzsbZMi/pbFm85YyyGcIcrRSjtw3xap/BR/hHkZVE=,tag:vb60+8JtYuPNOI8ltvbJng==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
