apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dfU9NykRJtxUIP270rGVtGaVpCwvZldMpBsRARe2BoU=,iv:XB5Vi3DwSkI9Lpqg/p6PaHxL3eToZngfNFgQJeRQ4p4=,tag:Wppc4DxZRQtztcE/jraMnQ==,type:str]
sops:
  age:
    - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOENXTnFoaW5kOFZPdytm
        bVgzd0NrdU1rZW5xM3ZFSHo3U01KNWRFd1J3CjB6ZlhBRExuaUU0QjE2NWdOTGVn
        T1RVME9SMlZpSS9vVTE0RkdNdmVMYVUKLS0tIDJObGwzTGpMME9YVzgzVldIVm4x
        Uy9YS1k0NDJYNUhBa0c3Y2xDNTZqbzQKxGbIGy1ny+Fngz/m6PD0zQaw/iFrhYkl
        TiyGzvsfMvSxifhlCxqR1rY/VaDLEZNwVwbL0a1F5QeYulrT+5B+2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T08:35:28Z"
  mac: ENC[AES256_GCM,data:BkMKR/1wnN8oj211ke/yczpXujFYxtYNT5s6f5JnDBRviUW+1f1+Rw3ybIcN4H8FzwVy7gKivnzzY5WkKrhY1AYr9Pyynd3VYvJdizTpLu1EseKblw9wMufyv1DOOxoivmSeRax9V/0auzoLK6+u75hWLCGcK5NQVYZg+LE1uBQ=,iv:wFsunAkUrkYraTeXTqsiDvcnGuD6GarktyDUbws7Fzk=,tag:IByfj+T+dwPD0V3eljts0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
