---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.devtom.ch"
      recordType: CNAME
      targets: ["bac59649-6cc6-474e-b8b6-55b246c60c75.cfargotunnel.com"]
    - dnsName: "external.k4s.ch"
      recordType: CNAME
      targets: ["bac59649-6cc6-474e-b8b6-55b246c60c75.cfargotunnel.com"]
