apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:p94D9kFyxVvYfFWH0p9wwGR06VMK5Yp5zJku6AgS5JJwxeaPEvXjvny23cEDvU1wT9rNyaDMcmoj9wX2wvVbwAb+U9ceTiuNu1+wEErg21ngdnyb7krACl31MBCSXKlRKbLcEmcHFl0yQLgIZKCfy/H/+zLNgJUG1MlC5oFxpjExUV4L3HucBfhsHyu8L8FGgfT9LMEyulChJ3fmrH7fcgW4cDCpYK74E60aPOOcWSGt2bhX,iv:u7pP3nhFfS/7vCbnN9gf7wZoZcDHALZAw+oWo+noYZU=,tag:bP9jCTYEb21wWmhbxXw6nA==,type:str]
sops:
  age:
    - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q1lDdk1uamdqRFgwVE9k
        RitxN2Jhdk1mblV3NG1VN2lqVXpBekJTNXpJCjV3RkgxTmZreTBPL1N1TnlsSk1h
        MlR1NVdpc0R5di9kT2NpNlY5WDJmVFkKLS0tIFoweDRpbVcwNHlEODI0aGJQZVNH
        QUoramNHdG04VStaVjFPUjk2bnZZVkUKCC4R55J64WCSvEWo3kHYAU9Wv+uROOEY
        TVdAG/nspBZQADNbC+wfWlLi0HCzp8nEQjJQrEaW1XOSYwDoEPDmKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T08:35:28Z"
  mac: ENC[AES256_GCM,data:5cRzNo9aBKwf3xSKQMvdi+wkgoaBOxmWA2PtdrR3r18allQGEKhdwOICvzpqrxFs5ANi/x7A8kDlpmyzeU2p2eocg/cmdzKS6byJEEqfCdNm/p7dV+YSQuVUeNictOihunYqjQmgwr3UVAWodGIHZYNY4KLoLSx9mJZh3kE7Y9U=,iv:GZ5DQF1Zzt8MbyejycI/bax+Krp2CiHWLgIY9uCZqf8=,tag:7sjPwjS8wQigfkW61GwoZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
