apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+2xJBQyB/voazmMQ/xMm8EaQMnZ81F9voCohtfUEHgTyuo1A4jH9eg==,iv:vBZg3w59iTu1LEzmS/69zOPaYazeBmLh1BLkeUhfw7s=,tag:aBxpzqEaVGvk36fSK3BK7A==,type:str]
sops:
  age:
    - recipient: age1mkywqnnqdskgay4tl99ukk8hkxhk5nhw652lcms2gtxzfxnufc6s99e25m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaGNkUkc1TmEwUFlkYTlL
        WkZkQ1JxVkdrbEhvODVVNHRKSkt0SE44VkNzCjZhZmkrdUxCNll2YVlkWTRFSTls
        QUQrdWtnRTQ3OW8wVVo0Y0dKMzc3NTAKLS0tIDZlU3ZOaDNGeExyZ3ZTK2ZpVkNt
        OWhTSmlLRnlLSHJ2dTRUR2tYVXhQT3MK0Eew60lXChmUYZo2p5aS3jB7HUrFnCvE
        MJiGdm8G7uVwDODK8TJ3VPo8bpWily8mxkbmgjJwIQzl7upDdb5GeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T08:35:28Z"
  mac: ENC[AES256_GCM,data:FFpM9G6TDOXLNkvGuFiQo7+RYAAbXj9aGAYUo6+nq4m9jLx7HCM0QRx08EKR/qMvwBsVJRAL4zrd2+fdTzS1N2ziad1FWMK/SkbS0H2Bo2nTuUXr18bdcpovYiequ9UZ+7B8kJkA4eEAc+nzWg1ndsg8qn9UKe/urV2WO0Nkxn0=,iv:1Bo1WdV2wE7i3xCjmQJomqj7e4SxLbz3s5DTZGwSMe4=,tag:47Ip/7BeB8PLhpsCXVcBWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
