---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.4.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.4.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "am6-1"
    ipAddress: "192.168.4.11"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7c8c7efaccccd9ba1c22d68c3479f69dfa1c253186f1294ad4a89aac9e4a44f7
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "1c:83:41:41:14:5c"
        dhcp: false
        addresses:
          - "192.168.4.11/24"
        routes:
          - gateway: "192.168.4.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.4.10"
  - hostname: "am6-2"
    ipAddress: "192.168.4.12"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7c8c7efaccccd9ba1c22d68c3479f69dfa1c253186f1294ad4a89aac9e4a44f7
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "1c:83:41:41:16:06"
        dhcp: false
        addresses:
          - "192.168.4.12/24"
        routes:
          - gateway: "192.168.4.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.4.10"
  - hostname: "n100-1"
    ipAddress: "192.168.4.16"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7c8c7efaccccd9ba1c22d68c3479f69dfa1c253186f1294ad4a89aac9e4a44f7
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:d0:43:e3"
        dhcp: false
        addresses:
          - "192.168.4.16/24"
        routes:
          - gateway: "192.168.4.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.4.10"
  - hostname: "n100-2"
    ipAddress: "192.168.4.17"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7c8c7efaccccd9ba1c22d68c3479f69dfa1c253186f1294ad4a89aac9e4a44f7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e8:ff:1e:d1:98:d1"
        dhcp: false
        addresses:
          - "192.168.4.17/24"
        routes:
          - gateway: "192.168.4.1"
            network: 0.0.0.0/0
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-ceph-usb.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-openebs.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-system-upgrades.yaml"

