apiVersion: v1alpha1
kind: RawVolumeConfig
name: replicated-storage
provisioning:
  diskSelector:
    match: "system_disk"
  minSize: 400GB
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: "system_disk"
  minSize: 100GB
  maxSize: 100GB
  grow: false
