---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "casetta-production"
spec:
  dnsNames:
    - "devtom.ch"
    - "*.devtom.ch"
    - "k4s.ch"
    - "*.k4s.ch"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "casetta-production-tls"
  usages:
    - digital signature
