---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: home-assistant
  interval: 1h
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.3.2@sha256:7d5095b0c431b830f1fa0e3a8940cea6a601ce181fea1c426d8a3c94ad5aa845
            env:
              TZ: Europe/Zurich
              HASS_HTTP_TRUSTED_PROXY_1: 192.168.4.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.111.0@sha256:d7a7c0188e942c53e7725dc7b7990086e1701557330f7db179fa270813544dcc
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      sonos:
        externalName: "{{ .Release.Name }}-sonos"
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: 192.168.4.34
        ports:
          tcp:
            port: 1400
            protocol: TCP
      app:
        primary: true
        ports:
          http:
            primary: true
            appProtocol: kubernetes.io/ws
            port: 8123
          http-code:
            port: 12321
            protocol: TCP
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: "{{ .Release.Name }}"
                port: 8123
        hostnames:
          - "{{ .Release.Name }}.devtom.ch"
          - "{{ .Release.Name }}.k4s.ch"
          - "ha.devtom.ch"
          - "ha.k4s.ch"
        parentRefs:
          - name: envoy-external
            namespace: network
      code-server:
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: "{{ .Release.Name }}"
                port: 12321
        hostnames:
          - "ha-code.devtom.ch"
          - "ha-code.k4s.ch"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /config/.venv
      tmp:
        type: emptyDir
